### PR TITLE
Lab 8

### LINKED ISSUE #498: [Web]: Create quiz page
### Issue Type

Deliverable

### Issue Description

A simple song prediction quiz page

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ekrembal**
Closes #498

### CODE REVIEW

**Comment by Enestst** [comment]
I wrote the Mobile App Testing Strategies for the Lab PR.
https://github.com/bounswe/bounswe2024group3/wiki/Mobile-App-Testing-Strategies

**Comment by batuhansolmaz** [comment]
https://github.com/bounswe/bounswe2024group3/wiki/Backend-Testing-Strategies
I wrote testing strategies in backend

**Comment by Abdusshh** [comment]
Here are the other issues and wiki pages related to Lab 8:
API Documentation: https://github.com/bounswe/bounswe2024group3/wiki/API-Documentation and https://github.com/bounswe/bounswe2024group3/issues/493
Primary features: https://github.com/bounswe/bounswe2024group3/issues/488
Testing strategies for web: https://github.com/bounswe/bounswe2024group3/issues/489
Testing strategies for backend: https://github.com/bounswe/bounswe2024group3/issues/491
Testing strategies for mobile: https://github.com/bounswe/bounswe2024group3/issues/494
Standards: https://github.com/bounswe/bounswe2024group3/issues/490
Meeting notes: https://github.com/bounswe/bounswe2024group3/issues/495
Domain specific features: https://github.com/bounswe/bounswe2024group3/issues/492

**Comment by jorgeveji112** [comment]
I wrote the WAI-ARIA Standard page on the wiki for the Lab PR
https://github.com/bounswe/bounswe2024group3/wiki/WAI‐ARIA-Documentation

**Comment by eyusufatik** [comment]
I wrote [https://github.com/bounswe/bounswe2024group3/wiki/API-Documentation], closes #493

**Comment by Enestst** [comment]
Prepared the meeting notes. You can see:
https://github.com/bounswe/bounswe2024group3/wiki/03.12.24-Meeting-Notes

**Pull request merged**
