### PR TITLE
Add a change theme button for UX.

### PR DESCRIPTION
**Pull request by Enestst**

### CODE REVIEW

**Comment by Enestst** [comment]
Meeting notes URL for the Lab 6:
https://github.com/bounswe/bounswe2024group3/wiki/12.11.24-Meeting-Notes

**Comment by Enestst** [comment]
User stories for LAB 6:
https://github.com/bounswe/bounswe2024group3/wiki/User-Story-1
https://github.com/bounswe/bounswe2024group3/wiki/User-Story-2

**Comment by jorgeveji112** [comment]
Issue #430 related

**Comment by Abdusshh** [comment]
LGTM!

**Pull request merged**
