### PR TITLE
Accessibility for Web Standards

### PR DESCRIPTION
**Pull request by jorgeveji112**
Creation Of Accessibility Component and implementation in header for Web Standards

### CODE REVIEW

**Comment by Abdusshh** [comment]
Create PR issue: https://github.com/bounswe/bounswe2024group3/issues/372

**Comment by yspolatt** [comment]
We revised the nonfunctional requirements according to our new chosen standards.

[Here is the issue.](https://github.com/bounswe/bounswe2024group3/issues/370)

**Comment by Enestst** [comment]
Revised the functional user requirements according to our newly chosen standards.

[Here is the issue.](https://github.com/bounswe/bounswe2024group3/issues/373)

**Comment by Enestst** [comment]
Here is the meeting notes of the day.

[Here is the meeting notes.](https://github.com/bounswe/bounswe2024group3/wiki/5.11.24-Meeting-Notes)

**Comment by jorgeveji112** [comment]
On these commit we created a custom React hook, useAccessibility, that tracks whether the user's last interaction was with the mouse or keyboard. On keyboard focus, it reads the aria-label of the focused element using speech synthesis, unless the last interaction was with the mouse. Event listeners are cleaned up when the component unmounts.

We also added the aria-labels on the header.

**Comment by Enestst** [comment]
I reviewed and merging the PR.

**Pull request merged**
